name: dev-deployment

on:
  push:
    branches:
      - development

jobs:

  dockerize:

    name: Build and Publish Docker
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        name: git pull n checkout

      - name: create env file
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_APP_PORT: ${{ secrets.APP_PORT }}
          envkey_APP_JWT_SECRET: ${{ secrets.APP_JWT_SECRET }}
          envkey_APP_DB_USER: ${{ secrets.APP_DB_USER }}
          envkey_APP_DB_PASS: ${{ secrets.APP_DB_PASS }}
          envkey_APP_DB_PORT: ${{ secrets.APP_DB_PORT }}
          envkey_APP_DB_HOST: ${{ secrets.APP_DB_HOST }}
          envkey_APP_DB_NAME: ${{ secrets.APP_DB_NAME }}
          file_name: .env
          fail_on_empty: true

      - name: login to docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: build & push Docker image
        run: |
          docker compose -f deployment/build.yml up
          docker push ovrrtd/agmc:latest


  deploy:
    name: Deploy to EC2 on development branch push
    runs-on: ubuntu-latest
    needs: dockerize
    steps:
      - name: git pull n checkout
        uses: actions/checkout@v2
      
      - name: deploy to aws
        env:
          AWS_HOST: ${{ secrets.AWS_HOST }}
          AWS_USERNAME: ${{ secrets.AWS_USERNAME }}
          AWS_PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY }}
        run: |
          echo "$AWS_PRIVATE_KEY" > private_key && chmod 400 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${AWS_USERNAME}@${AWS_HOST} '
            docker pull ovrrtd/agmc:latest &&
            docker stop agmc-api || true &&
            docker rm agmc-api || true &&
            docker run -d --network host --name agmc-api agmc:latest ./main -migrate=migrate &&
            docker run -d --network host --name agmc-api agmc:latest ./main &&
          '